name: CI
  
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout main
      uses: actions/checkout@v2
      
    - name: Checkout to
      uses: actions/checkout@v2
      with:
         repository: DmitrijOkeanij/SunEngineBuild
         path: SunEngineBuild
      
    - name: Make files  
      run: |
        echo "1234" > ./file2.txt
        echo "4565" > ./file3.txt
        echo "4565" > ./fww3.txt
        echo "4565" > ./fiddle3.txt
        cd SunEngineBuild
        echo "1234" > ./file2.txt
        echo "4565" > ./file3.txt
        echo "4565" > ./fww3.txt
        echo "4565" > ./fiddle3.txt
        ls -la
   
    - name: Commit build
      uses: EndBug/add-and-commit@v2
      with:
         author_name: SunEngine GitHub Action Script
         author_email: github-action@sunengine.site
         cwd: "./SunEngineBuild/"
         message: "Build auto commit"
         path: "."
         pattern: "*.txt"
         force: true
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
