name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout main
      uses: actions/checkout@v2
      
    - name: Checkout to
      uses: actions/checkout@v2
      with:
         repository: DmitrijOkeanij/SunEngineBuild
         path: SunEngineBuild
      
    - name: Make files  
      run: |
        mkdir zzz
        echo "1234" > ./SunEngineBuild/file2.txt
        echo "4565" > ./SunEngineBuild/file3.txt
        echo "4565" > ./SunEngineBuild/fww3.txt
        echo "4565" > ./SunEngineBuild/fiddle3.txt
        echo ".git/" > ./SunEngineBuild/.gitignore
        
    #- name: Push
    #  uses: seanmiddleditch/gha-publish-to-git@master
    #  with:
    #    repository: DmitrijOkeanij/SunEngineBuild
    #    branch: master
    #    host: github.com  
    #    github_token: '${{ secrets.GITHUB_TOKEN  }}'
    #    github_pat: '${{ secrets.GH_PAT  }}'
    #    source_folder: ./zzz
    #    working_directory: wd1
    #    #target_folder: .
    
    - name: Commit build
      uses: DmitrijOkeanij/add-and-commit@v2.4.0
      with:
         author_name: SunEngine GitHub Action Script
         author_email: github-action@sunengine.site
         cwd: "./SunEngineBuild/"
         message: "Build auto commit"
         path: "."
         pattern: "*"
         force: true
      env:
         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
