name: CI
  
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout main
      uses: actions/checkout@v2
      
   #- name: Checkout to
   #   uses: actions/checkout@v2
   #   with:
   #      repository: DmitrijOkeanij/SunEngineBuild
   #      path: SunEngineBuild
      
    - name: Make files  
      run: |
        mkdir zzz
        echo "1234" > ./zzz/file2.txt
        echo "4565" > ./zzz/file3.txt
        echo "4565" > ./zzz/fww3.txt
        echo "4565" > ./zzz/fiddle3.txt
   
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: DmitrijOkeanij/SunEngineBuild
        branch: master
        github_token: '${{ secrets.GITHUB_TOKEN  }}'
        github_pat: '${{ secrets.GH_PAT  }}'
        source_folder: zzz
      if: success() && github.event == 'push'
