name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Make files  
      run: |
        mkdir updir
        echo "123" > ./updir/file.txt
        echo "456" > ./updir/file2.txt
        cd ./updir/
        ls -la
        echo "HALLOW WORLD!"
        cd ..
   
    - name: publish:starters
      uses: johno/actions-push-subdirectories@master
      env:
          API_TOKEN_GITHUB: ${{ secrets.AutoBuild }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: updir DmitrijOkeanij SunEngineBuild
