name: CI
    
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout main
      uses: actions/checkout@v2
      with:
         path: test1
        
    #- name: Checkout to
    #  uses: actions/checkout@v2
    #  with:
    #     repository: DmitrijOkeanij/SunEngineBuild
    #     path: SunEngineBuild
      
    - name: Make files  
      run: |
        ls -la
        rm -rf *
        mkdir zzz
        echo "1111" > ./zzz/testiiia.txt
        echo "1234" > ./zzz/file2.txt
        echo "4565" > ./1.txt
        echo "4565" > ./2.txt
        echo "4565" > ./3.txt
        ls -la
        #cd zzz
        #echo ".git/" > ./SunEngineBuild/.gitignore
        
    #- name: Push
    #  uses: seanmiddleditch/gha-publish-to-git@master
    #  with:
    #    repository: DmitrijOkeanij/SunEngineBuild
    #    branch: master
    #    host: github.com  
    #    github_token: '${{ secrets.GITHUB_TOKEN  }}'
    #    github_pat: '${{ secrets.GH_PAT  }}'
    #    source_folder: ./zzz
    #    working_directory: wd1
    #    #target_folder: .
    
    #- name: Commit build
    #  uses: DmitrijOkeanij/add-and-commit@master
    #  with:
    #     author_name: SunEngine GitHub Action Script
    #     author_email: github-action@sunengine.site
    #     cwd: "./SunEngineBuild/"
    #     message: "Build auto commit"
    #     path: "."
    #     pattern: "*"
    #     force: true
    #  env:
    #     GITHUB_TOKEN: ${{ secrets.T1 }}
        
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: git@github.com:DmitrijOkeanij/SunEngineBuild.git
        BRANCH: master
        SSH_PRIVATE_KEY: ${{ secrets.PRIV }}
        FOLDER: .
