name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      
    - uses: actions/checkout@v2
      with:
        repository: DmitrijOkeanij/SunEngineBuild
        path: "./secondRepo/"

    - run: |
        cp ./test.txt ./secondRepo/
        echo "123" > ./secondRepo/file.txt
        cd ./secondRepo/
        ls -la
        echo "HALLOW WORLD!"
        cd ..
   
    - name: Commit build 
      uses: EndBug/add-and-commit@v2
      with:
         author_name: SunEngine GitHub Action Script
         author_email: github-action@sunengine.site
         cwd: "secondRepo"
         message: "Build auto commit"
         path: "."
         pattern: "*.*"
         force: true
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
