name: CI
  
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Make files  
      run: |
        mkdir updir
        cd ./updir
        mkdir z1
        cd ./z1
        echo "123" > ./file.txt
        echo "456" > ./file2.txt
        
        ls -la
        echo "HALLOW WORLD!"
        cd ../..
   
    - name: publish:starters
      uses: johno/actions-push-subdirectories@master
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: updir DmitrijOkeanij SunEngineBuild
