name: CI
  
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Make files  
      run: |
        mkdir updir
        cd ./updir
        mkdir z1
        cd ./z1
        echo "123" > ./file.txt
        echo "456" > ./file2.txt
        echo "{\"name\":\"SunEngineBuild\"}" > ./package.json
        ls -la
        echo "HALLOW WORLD!"
        cd ../..
   
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: master
        github_token: '${{ secrets.GITHUB_TOKEN  }}'
        github_pat: '${{ secrets.GITHUB_TOKEN }}'
        source_folder: updir/z1
      if: success() && github.event == 'push'
